---
- name: Create complex condition
  hosts: all
  vars:
    my_package:
      - jre8
      - dropbox
  tasks:
  - name: Install packages
    win_chocolatey:
      name: "{{item}}"
      state: present
      loop: "{{my_package}}"
    when: (ansible_facts['distribution'] == "Microsoft Windows Server 2016 Core" and ansible_facts['architecture'] == "64-bit") and (ansible_facts['date_time'] ['date'] == "2019-11-21" or ansible_facts['date_time]['month'] == 11) or ansible_facts['version'] ==10 