---
- name: Create user and add user in group
  hosts: all
  tasks:
  - name: Create a new group
    win_group:
      name: Deploy
      description: Deploy Group
      state: present
  - name: Create user name John
      win_user:
        name: John
        state: present
        groups:
        - Deploy