---
- name: Testing handlers
  hosts: all
  tasks:
  - name: Install Winrar
    win_chocolatey:
      name: winrar
      state: present
    notify: 
    - reboot server
  - name: failing the task
    debug:
      msg: failing the task as testing requires
    ignore_errors: true
  - name: This is another tasks
    debug:
      final task
  handlers:
  - name: reboot server
    win_reboot:
    