---
- name: Testing simple loops
  hosts: all
  tasks: 
  - name: install packages
    win_chocolatey:
      name: "{{item}}"
      state: present
    loop:
    - jre8
    - javaruntime-preventasktoolbar
    - dropbox